### ISSUE TITLE
godotenvvault proxying commands to godotenv

### ISSUE THREAD

**Issue by motdotla** [dotenv-org/godotenvvault#1]
As a first step, get `godotenvvault` proxying all exposed commands from `godotenv`. 

This way, I should be able to follow the current README in this repo, and it just works.

For example, after this issue is completed I can do the following:

1. Install

```
go get github.com/dotenv-org/godotenvvault
```

2. Use

```
HELLO="World"
```

```go
package main

import (
    "log"
    "os"

    "github.com/joho/godotenvvault"
)

func main() {
  err := godotenvvault.Load()
  if err != nil {
    log.Fatal("Error loading .env file")
  }

  hello := os.Getenv("HELLO")
  
  log.Println(hello) // world
}
```

This issue/ticket includes all the work to have the library versioned, installable, etc.

In later tickets we'll add the .env.vault decryption logic.

**Comment by ian-ross** [comment]
This should now work. For the latest version of Go (v1.20), you can only install packages from within a module. So you need to make a file called `go.mod` with the following contents:

```
module github.com/dotenv-org/demo

go 1.20

require github.com/dotenv-org/godotenvvault v0.1.0

require github.com/joho/godotenv v1.5.1 // indirect
```

Then you can put your code in a file called `demo.go` or something and do `go build demo.go`. The compiler will give you some instructions about how to download the necessary dependencies, and after doing those things, `go build demo.go` should produce a `demo` executable.

For reference, the commands the compiler will tell you to run will be something like this:

```
go mod download github.com/dotenv-org/godotenvvault
go get github.com/dotenv-org/godotenvvault@v0.1.0
```

(I checked with an older v1.17 version of Go, and things are a little different. Using the `go.mod` file still works, and the compiler still gives you instructions to follow, but they're a little different from the latest compiler version. Let me know if you have any trouble. I'll eventually add detailed instructions to the README, but this should be enough to get us going.)

**Comment by motdotla** [comment]
Awesome. Marking done.
