### ISSUE TITLE
Clear documentation of `DOTENV_KEY` format

### ISSUE THREAD

**Issue by ian-ross** [dotenv-org/godotenvvault#3]
It's not clear from the documentation how exactly the password field of `DOTENV_KEY` values should be interpreted. There are two variants appearing in the different language APIs.

The Ruby one takes the [last 64 characters of the password field](https://github.com/dotenv-org/dotenv-vault-ruby/blob/master/lib/dotenv-vault.rb#L181) of the `DOTENV_KEY` URL:

```ruby
    key = key[-64..-1] # last 64 characters. allows for passing keys with preface like key_*****
```

The JS SDK [takes the last 64 characters of the password field](https://github.com/dotenv-org/dotenv-vault-core/blob/master/lib/main.js#L66):

```javascript
  const key = Buffer.from(keyStr.slice(-64), 'hex')
```

But the Python SDK [drops the first 4 characters of the password field](https://github.com/dotenv-org/python-dotenv-vault/blob/master/src/dotenv_vault/vault.py#L72):

```python
        _key = key[4:]
```

This means that the Python version will only work the same as the other versions as long as the prefix to the password field is 4 characters (e.g. "`key_`"). If it's any other length, the different SDKs will behave differently.

So far, I've been working mostly by comparing with the Python code, since I'm more familiar with that than Ruby, but I guess that the Python code isn't correct there, is it?

Can I just confirm that the JS and Ruby versions have the correct behavior here?

**Comment by motdotla** [comment]
Oof, the python one is wrong.

It should take the last 64.

**Comment by ian-ross** [comment]
OK, thanks — I'll fix the Go code to work that way tomorrow.

**Comment by ian-ross** [comment]
Fixed by https://github.com/dotenv-org/godotenvvault/commit/0aa164ea9108164563c1241991faf5c641f8e404
