### ISSUE TITLE
Issue: Environment Variables Not Loading in Tests

### ISSUE THREAD

**Issue by DarkHeros09** [dotenv-org/godotenvvault#8]
Hi,

A friend recommended Dotenv-Vault to me, and I loved it. However, I'm currently experiencing an issue when running my tests.

When I run my Go application normally, it loads my environment variables without any problems. However, when I run my tests, the values are empty.

My tests are located in a subdirectory, and although the environment file is being loaded, the variables are not being populated correctly.

Steps to Reproduce

1. Place the .env file in the root directory.
2. Place the test files in a subdirectory.
3. Use Dotenv-Vault to load the environment variables.
4. Run the Go application normally and observe that the environment variables load correctly.
5. Run the tests and observe that the environment variables are empty.

env_test.go
```go
package env

import (
	"fmt"
	"testing"

	"github.com/dotenv-org/godotenvvault"
)

func TestEnvVars(t *testing.T) {
	appEnv, err := godotenvvault.Read("../.env.vault")

	if err != nil {
		t.Fatalf("Error loading .env file")
	}

	if appEnv["DB_DRIVER"] == "" {
		t.Fatalf("Environment variable DB_DRIVER is empty")
	}

	fmt.Println("MY_ENV_VAR:", appEnv["DB_DRIVER"])
}
```

EDIT: when i load ```../.env``` instead of ```../.env.vault``` it loads fine.

**Comment by motdotla** [comment]
do you have your DOTENV_KEY set before running the tests?

using dotenvx to actually do the running here might be easier. it has great debugging - among other things. 

```
dotenvx run --debug -- yourgocommandbinary
```

with DOTENV_KEY

```
DOTENV_KEY=yourtestkey dotenvx run -- yourbinary
```

**Comment by DarkHeros09** [comment]
yes, i just tried dotenx and everything went great both locally and on github actions..... great tool.

although i had to install the executable on windows to make work, as on docker image it didn't recognize the go command.
I'll open an issue about once i make sure the problem is not on my end.

i really appreciate your work. thank you for the help.
